### ISSUE TITLE
Update to Python version 3.11.0

### ISSUE THREAD

**Issue by dariru3** [Codecademy/add-automated-tests-off-platform-project#168]
Set up Python fails using 3.10.0

Updating the yaml file to use 3.11.0 successfully runs the test

```
name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest
```
