### ISSUE TITLE
Python-version: 3.10.0 arch: x64

### ISSUE THREAD

**Issue by ghost** [Codecademy/add-automated-tests-off-platform-project#261]
..old versjon of python couses issues on test unit

**Comment by RonnieX10** [comment]
change yaml python version to 3.12.1 it work

```
name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest
```
