### ISSUE TITLE
[BUG] Error: Version 3.10.0 with arch x64 not found

### ISSUE THREAD

**Issue by gitleye** [Codecademy/add-automated-tests-off-platform-project#274]
hey team, 

when I ran the command `git push --set-upstream origin "add-auto-tests"` while following the instructions on the codeacademy - https://www.codecademy.com/courses/learn-git/articles/github-actions-tutorial-on-automated-testing

my GitHub actions returned the error message `Error: Version 3.10.0 with arch x64 not found` attached.
<img width="1089" alt="Screenshot 2024-02-10 at 1 02 39 PM" src="https://github.com/Codecademy/add-automated-tests-off-platform-project/assets/41123124/2d8611ce-ae89-4e03-b4d1-6375d934b846">

if the python-version on the unittests.yaml file could be updated to a version that's currently available in the following [library][https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json], that would be greatly appreciated. 

thank you

contents of unittests.yaml file in `add-automated-tests-off-platform-project/.github/workflows/unittests.yaml`
```
name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest
```

**Comment by kylestarr** [comment]
Try updating `python-version: 3.10.0` to `python-version: "3.10"`. Mind the quotes around `"3.10"`. This triggered a successful build for me.

```
name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest
```
